## Colors configuration
colors:
  # Default colors
  primary:
    background: '#2a3344'
    foreground: '#d8dee9'

  # Normal colors
  normal:
    black:   '#1a1a1a'
    red:     '#bc245d'
    green:   '#2eb398'
    yellow:  '#d48e15'
    blue:    '#3689e6'
    magenta: '#bf59ad'
    cyan:    '#0e9a83'
    white:   '#abacae'

  # Bright colors
  bright:
    black:   '#4d4d4d'
    red:     '#f4679d'
    green:   '#63d4bd'
    yellow:  '#ffe16b'
    blue:    '#64baff'
    magenta: '#cd7ebf'
    cyan:    '#43d6b5'
    white:   '#d4d4d4'
