#!/usr/bin/env sh
# Terminate already running bar instances
killall -q polybar 
# Wait until the processes have been shut down
# while pgrep -x polybar >/dev/null; do sleep 1; done
# Launch
polybar -q main -c ~/.config/i3/polybar/i3bar.ini &
polybar -q extra -c ~/.config/i3/polybar/i3bar.ini &
