#Theme name : f1tzl4nd Google

*.foreground:   #C5C8C6
*.background:   #1D1F21
*.cursorColor:  #C5C8C6
*fading: 35
*fadeColor: #1D1F21

*.color0: #1D1F21
*.color1: #CC342B
*.color2: #198844
*.color3: #FBA922
*.color4: #3971ED
*.color5: #A36AC7
*.color6: #22DCED
*.color7: #C5C8C6
*.color8: #969896
*.color9: #CC5B54
*.color10: #348854
*.color11: #FBBC53
*.color12: #6791ED
*.color13: #B291C7
*.color14: #4FE0ED
*.color15: #FFFFFF
