#Theme name : f1tzl4nd Adapta

*.foreground:   #dfdfdf
*.background:   #212b30
*.cursorColor:  #dfdfdf
*fading: 35
*fadeColor: #212b30

*.color0: #222D32
*.color1: #00bcd4
*.color2: #16a085
*.color3: #323d42
*.color4: #2d4348
*.color5: #4DB6AC
*.color6: #566067
*.color7: #b9c2c7
*.color8: #2f3d44
*.color9: #00def6
*.color10: #16c0a5
*.color11: #384449
*.color12: #315054
*.color13: #449690
*.color14: #677176
*.color15: #cfd8dc
