#! /bin/sh

# Set display from arandr saved script
sh ~/.screenlayout/monitor-debian.sh &

bspc monitor DP-2 -d term code ofc grfx misc 
bspc monitor DP-1 -d web chat file mdia util
bspc config focus_on_window_activation	urgent

bspc config border_width			2
bspc config window_gap				5

bspc config split_ratio				0.55
bspc config single_monocle			false
bspc config focus_follows_pointer	true
bspc config borderless_monocle		true
bspc config gapless_monocle			true

bspc config presel_feedback_color "#3B3D41"
bspc config active_border_color		"#42a5f5"
bspc config focused_border_color "#61c766"
bspc config normal_border_color "#27292D"

## 5 > office and docs (always open office/doc apps on workspace-3)
declare -a ofc=(libreoffice-writer libreoffice-calc libreoffice-impress \
libreoffice-startcenter libreoffice Soffice *:libreofficedev *:soffice)
for i in ${ofc[@]}; do
   bspc rule -a $i desktop='^3' follow=on focus=on; done

bspc rule -a qimgv state=floating
bspc rule -a Xarchiver state=floating
bspc rule -a Galculator state=floating
bspc rule -a mpv state=floating 
bspc rule -a Pavucontrol:pavucontrol state=floating 
bspc rule -a Lxappearance state=floating 
bspc rule -a 'GitHub Desktop' desktop='^2' follow=on
bspc rule -a Alacritty desktop='^1' follow=on
bspc rule -a Code='^2' follow=on
bspc rule -a Gimp desktop='^4' follow=on
bspc rule -a Inkscape desktop='^4' follow=on
bspc rule -a Google-chrome desktop='^6' follow=on
bspc rule -a discord desktop='^7' follow=on
bspc rule -a Thunar desktop='^8' follow=on
bspc rule -a Spotify desktop='^9' follow=on

# fix some Java applications
wmname LG3D

# Autostart
#
# Cursor
xsetroot -cursor_name left_ptr &
# Polkit
/usr/lib/policykit-1-gnome/polkit-gnome-authentication-agent-1 &
# Notifications
dunst -config ~/.config/bspwm/dunst/dunstrc &
picom --config ~/.config/bspwm/picom/picom.conf --animations -b &
feh --bg-fill ~/.config/bspwm/wallpaper/wallhaven-vq76dp_3440x1440.png &
#~/.fehbg

## Polybar or tint
~/.config/bspwm/polybar/polybar-bspwm &

## apps for systray if enabled
# volumeicon &
pgrep nm-applet > /dev/null || nm-applet &
blueman-applet &
pgrep dropbox || sh ~/.dropbox-dist/dropboxd &


# (re)load sxhkd for keybinds
if hash sxhkd >/dev/null 2>&1; then
	pkill sxhkd
	sleep 0.5
	sxhkd -c "$HOME/.config/bspwm/sxhkd/sxhkdrc" &
fi
