#!/usr/bin/env bash

## Copyright (C) 2020-2021 Aditya Shakya <adi1090x@gmail.com>
## Everyone is permitted to copy and distribute copies of this file under GNU-GPL3

## Environtment
export PATH="${PATH}:$HOME/.config/bspwm/bin"

# Set display from arandr saved script
sh ~/.screenlayout/monitor.sh &


## Get colors from .Xresources -------------------------------#
xrdb ~/.Xresources
getcolors() {
	FOREGROUND=$(xrdb -query | grep 'foreground:'| awk '{print $NF}')
	BACKGROUND=$(xrdb -query | grep 'background:'| awk '{print $NF}')
	BLACK=$(xrdb -query | grep 'color0:'| awk '{print $NF}')
	RED=$(xrdb -query | grep 'color1:'| awk '{print $NF}')
	GREEN=$(xrdb -query | grep 'color2:'| awk '{print $NF}')
	YELLOW=$(xrdb -query | grep 'color3:'| awk '{print $NF}')
	BLUE=$(xrdb -query | grep 'color4:'| awk '{print $NF}')
	MAGENTA=$(xrdb -query | grep 'color5:'| awk '{print $NF}')
	CYAN=$(xrdb -query | grep 'color6:'| awk '{print $NF}')
	WHITE=$(xrdb -query | grep 'color7:'| awk '{print $NF}')
}
getcolors

## Configurations --------------------------------------------#
#workspaces() {
#	name=1
#	for monitor in `bspc query -M`; do
#		bspc monitor ${monitor} -n "$name" -d 'I' 'II' 'III' 'IV' 'V'
		#bspc monitor ${monitor} -n "$name" -d '' '' '' ''
#		let name++
		#bspc monitor ${monitor} -n "$name" -d '' '' '' ''
#		bspc monitor ${monitor} -n "$name" -d 'VI' 'VII' 'VIII' 'IX' 'X'
#	done
#}
#workspaces

bspc monitor DP-4 -d 1 2 3 4 5
bspc monitor DP-0 -d 6 7 8 9 10
#bspc monitor -d 'I' 'II' 'III' 'IV' 'V' 'VI' 'VII' 'VIII'

bspc config border_width 1
bspc config window_gap 10
bspc config split_ratio 0.50

bspc config focused_border_color "$BLUE"
bspc config normal_border_color "$BACKGROUND"
bspc config active_border_color "$MAGENTA"
bspc config presel_feedback_color "$GREEN"

bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config paddingless_monocle true
bspc config single_monocle false
bspc config focus_follows_pointer true

## Window rules ----------------------------------------------#

# remove all rules first
bspc rule -r *:*

# 1 > terminal
declare -a term=(Alacritty Xfce4-terminal Gnome-terminal)
for i in ${term[@]}; do
   bspc rule -a $i desktop='^1' follow=on focus=on; done

# 2 > web
bspc rule -a firefox desktop='^2' follow=on focus=on
bspc rule -a firefoxdeveloperedition desktop='^2' follow=on focus=on
bspc rule -a chromium desktop='^2' follow=on focus=on

# 3 > grfx
declare -a grfx=(Inkscape Gimp-2.10)
for i in ${grfx[@]}; do
   bspc rule -a $i desktop='^3' follow=on focus=on; done

# 4 > code
declare -a code=(Atom Code Gedit Geany code-oss)
for i in ${code[@]}; do
   bspc rule -a $i desktop='^4' follow=on focus=on; done

# 5 > office and docs
declare -a office=(Gucharmap Atril Evince \
libreoffice-writer libreoffice-calc libreoffice-impress \
libreoffice-startcenter libreoffice Soffice *:libreofficedev *:soffice)
for i in ${office[@]}; do
   bspc rule -a $i desktop='^5' follow=on focus=on; done

# 6 > Communication
declare -a comm=(Google-chrome Microsoft-edge-beta Thunderbird TelegramDesktop Hexchat)
for i in ${comm[@]}; do
   bspc rule -a $i desktop='^6' follow=on focus=on; done

# 7 > files
declare -a files=(Thunar Meld)
for i in ${files[@]}; do
   bspc rule -a $i desktop='^7' follow=on focus=on; done

# 8 > settings
bspc rule -a 'VirtualBox Manager' desktop='^8' follow=on focus=on
bspc rule -a GParted desktop='^8' follow=on focus=on
declare -a settings=(Lxappearance Lxtask Lxrandr Arandr \
System-config-printer.py Pavucontrol Exo-helper-1 \
Xfce4-power-manager-settings)
for i in ${settings[@]}; do
   bspc rule -a $i desktop='^8' state=floating follow=on focus=on; done

# 9 > media
declare -a media=(Audacity Music MPlayer Lxmusic obs)
for i in ${media[@]}; do
  bspc rule -a $i desktop='^7' state=floating follow=on focus=on; done

# special rules
declare -a floating=(alacritty-float Onboard Yad 'Firefox:Places' \
Viewnior feh Nm-connection-editor)
for i in ${floating[@]}; do
   bspc rule -a $i state=floating follow=on focus=on; done

bspc rule -a Conky state=floating manage=off
bspc rule -a stalonetray state=floating manage=off

## Autostart -------------------------------------------------#

# Kill if already running
killall -9 xsettingsd sxhkd dunst ksuperkey xfce4-power-manager

# Lauch notification daemon
dunst \
-geom "280x50-10+42" -frame_width "1" -font "Iosevka Custom 9" \
-lb "$BACKGROUND" -lf "$FOREGROUND" -lfr "$BLUE" \
-nb "$BACKGROUND" -nf "$FOREGROUND" -nfr "$BLUE" \
-cb "$BACKGROUND" -cf "$RED" -cfr "$RED" &

# Lauch xsettingsd daemon
xsettingsd &

# Dex
dex -a -s /etc/xdg/autostart/:~/.config/autostart/

# polkit agent
#if [[ ! `pidof xfce-polkit` ]]; then
#	/usr/lib/xfce-polkit/xfce-polkit &
#fi
if [[ ! `pidof lxpolkit` ]]; then
	/usr/bin/lxpolkit &
fi


# Lauch keybindings daemon
sxhkd -c $HOME/.config/bspwm/sxhkd/sxhkdrc &

# Enable Super Keys For Menu
ksuperkey -e 'Super_L=Alt_L|F1' &
ksuperkey -e 'Super_R=Alt_L|F1' &

# Enable power management
xfce4-power-manager &

# Network Applet
nm-applet &

# Fix cursor
xsetroot -cursor_name left_ptr

# Set Compose key
setxkbmap -option compose:rctrl &

# start blueberry app for managing bluetooth devices from tray:
blueberry-tray &

# Restore wallpaper
#bash $HOME/.fehbg
nitrogen --restore

# Start mpd
#exec mpd &

# Start dropbox
exec dropbox &

# Start bspwm scripts
bspcolors
bspbar
bspcomp
bspfloat &

# Fix non-parenting windows
wmname LG3D
