#!/usr/bin/env bash

## BSPWM config file

###############################################################
## General ---------------------------------------------------#
###############################################################

## Bspwm config directory
BSPDIR="$HOME/.config/bspwm"

## Export bspwm/bin dir to PATH
export PATH="${PATH}:$HOME/.config/bspwm/bin"

## Run java applications without issues
export _JAVA_AWT_WM_NONREPARENTING=1

# Fix non-parenting windows
wmname LG3D

###############################################################
## Current theme ---------------------------------------------#
###############################################################

## Load current theme files to get colors for bspwm
source "$BSPDIR"/themes/current.bash

## Get the wallpaper from theme file
CURRENT_WALLPAPER="$wallpaper"

## Get the colors from theme file
FOREGROUND="$foreground"
BACKGROUND="$background"
CURSOR="$cursor"
BLACK="$color0"
RED="$color1"
GREEN="$color2"
YELLOW="$color3"
BLUE="$color4"
MAGENTA="$color5"
CYAN="$color6"
WHITE="$color7"
ALTBLACK="$color8"
ALTRED="$color9"
ALTGREEN="$color10"
ALTYELLOW="$color11"
ALTBLUE="$color12"
ALTMAGENTA="$color13"
ALTCYAN="$color14"
ALTWHITE="$color15"

## Bspwm appearance
CURRENT_BORDER='2'
CURRENT_GAP='10'
CURRENT_SRATIO='0.50'

###############################################################
## Configurations --------------------------------------------#
###############################################################

## Manage Workspaces
#workspaces() {
#	name=1
#	for monitor in `bspc query -M`; do
#		#bspc monitor ${monitor} -n "$name" -d 'I' 'II' 'III' 'IV' 'V' 'VI' 'VII' 'VIII'
#		bspc monitor ${monitor} -n "$name" -d '' '' '' '' '' '' '' ''
#		let name++
#	done
#}
#workspaces
bspc monitor DP-4 -d '' '' '' '' ''
#bspc monitor DP-0 -d '' '' '' '' '' ''
bspc monitor DP-2 -d '' '' '' '' ''
#bspc monitor -d 'I' 'II' 'III' 'IV' 'V' 'VI' 'VII' 'VIII'


## Apply bspwm configurations
bspc config border_width "$CURRENT_BORDER"
bspc config window_gap "$CURRENT_GAP"
bspc config split_ratio "$CURRENT_SRATIO"

bspc config focused_border_color "$GREEN" 
bspc config normal_border_color "$BACKGROUND"
bspc config active_border_color "$BLUE"
bspc config presel_feedback_color "$MAGENTA"

bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config paddingless_monocle true
bspc config single_monocle true
bspc config focus_follows_pointer true

## Manage all the unmanaged windows remaining from a previous session.
bspc wm --adopt-orphans

###############################################################
## Window rules ----------------------------------------------#
###############################################################

# remove all rules first
bspc rule -r *:*

## 1 > terminal (always open terminal on workspace-1)
# 1 > terminal
declare -a term=(Alacritty Xfce4-terminal Gnome-terminal)
for i in ${term[@]}; do
   bspc rule -a $i desktop='^1' follow=on focus=on; done

## 2 > code (always open editors on workspace-4)
declare -a code=(Atom Code Gedit Geany Meld code-oss Xed)
for i in ${code[@]}; do
  bspc rule -a $i desktop='^2' follow=on focus=on; done

## 3 > office and docs (always open office/doc apps on workspace-3)
declare -a office=(Gucharmap Atril Evince \
libreoffice-writer libreoffice-calc libreoffice-impress \
libreoffice-startcenter libreoffice Soffice *:libreofficedev *:soffice)
for i in ${office[@]}; do
   bspc rule -a $i desktop='^3' follow=on focus=on; done

## 4 > grfx (always open grfx apps on workspace-4)
declare -a grfx=(Inkscape Gimp-2.10 Viewnior)
for i in ${grfx[@]}; do
   bspc rule -a $i desktop='^4' follow=on focus=on; done

## 5 > system (always open system apps on workspace-5)
bspc rule -a GParted desktop='^5' follow=on focus=on
bspc rule -a Pamac-manager desktop='^5' follow=on focus=on
declare -a settings=(Catfish KeePassXC Lxtask Lxrandr Arandr \
System-config-printer.py Pavucontrol Exo-helper-1 \
Xfce4-power-manager-settings)
for i in ${settings[@]}; do
   bspc rule -a $i desktop='^5' follow=on focus=on; done

## 6 > web (always open web browser on workspace-6)
declare -a web=(Google-chrome Microsoft-edge)
for i in ${web[@]}; do
   bspc rule -a $i desktop='^6' follow=on focus=on; done

## 7 > communication (always open communication apps on workspace-7)
declare -a chat=(chromium firefox-aurora Navigator Thunderbird TelegramDesktop Hexchat)
for i in ${chat[@]}; do
	bspc rule -a $i desktop='^7' follow=on focus=on; done

## 8 > files (always open file manager on workspace-8)
declare -a files=(Nautilus Pcmanfm Thunar qBittorrent)
for i in ${files[@]}; do
   bspc rule -a $i desktop='^8' state=tiled follow=on focus=on; done

## 9 > misc (always open media apps on workspace-9)
bspc rule -a 'VirtualBox Manager' desktop='^9' follow=on focus=on
bspc rule -a 'Mozilla VPN' desktop='^9' follow=on focus=on

## 10 > media (always open media apps on workspace-10)
declare -a media=(Audacity Music MPlayer Lxmusic obs spotify)
for i in ${media[@]}; do
   bspc rule -a $i desktop='^10' state=floating follow=on focus=on; done

# special rules
declare -a floating=(Onboard Yad 'Firefox:Places' \
Viewnior feh Nm-connection-editor)
for i in ${floating[@]}; do
   bspc rule -a $i state=floating follow=on focus=on; done

# spotify rule
	bspc config external_rules_command "$HOME/.config/bspwm/bin/spotify.sh"

bspc rule -a Conky state=floating manage=off
bspc rule -a stalonetray state=floating manage=off

###############################################################
## Autostart -------------------------------------------------#
###############################################################

# Set display from arandr saved script
sh ~/.screenlayout/monitor.sh &

# Kill if already running
killall -9 xsettingsd sxhkd dunst xfce-polkit xfce4-power-manager

# Lauch xsettingsd daemon
xsettingsd --config="$BSPDIR"/xsettingsd &

# polkit agent
#if [[ ! `pidof xfce-polkit` ]]; then
#	/usr/lib/xfce-polkit/xfce-polkit &
#fi

# Launch keybindings daemon
sxhkd -c "$BSPDIR"/sxhkdrc &

# Enable power management
xfce4-power-manager &

# Fix cursor
xsetroot -cursor_name left_ptr

# Set Compose key
setxkbmap -option compose:rctrl &

# Dex
dex -a -s /etc/xdg/autostart/:~/.config/autostart/  

# Network Applet
nm-applet --indicator &

# start blueberry app for managing bluetooth devices from tray:
blueberry-tray &

# Pamac-stalonetray
#pamac-tray &

# Restore wallpaper
feh --no-xinerama --no-fehbg --bg-scale "$CURRENT_WALLPAPER"
#bash $HOME/.fehbg

# Start dropbox
exec dropbox &

# Start mpd
#exec mpd &

# Start bspwm scripts
bspcolors
bspbar
bspcomp
bspdunst
bspfloat &
